name: Deploy Cluster

on:
  push:
    branches:
      - main

jobs:
  Deploy-to-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t ttl.sh/hello-world:5m .
        docker push ttl.sh/hello-world:5m

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.8.0
      with:
        version: v0.20.0
        config: cluster.yml
        cluster_name: static

    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f pod.yml
        kubectl wait --for=condition=Ready pods --all

    - name: Check Pod NodePort
      id: check-nodeport
      run: |
        nodeport=$(kubectl get svc hello-world-service -o jsonpath='{.spec.ports[0].nodePort}')
        echo "The Hello World pod is accessible at NodePort: $nodeport"
        echo "::set-output name=nodeport::$nodeport"
  
    - name: Check App with curl
      run: |
        nodeport="${{ steps.check-nodeport.outputs.nodeport }}"
        curl http://localhost:${nodeport}
